In [9]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import seaborn as sns
import matplotlib.pyplot as plt

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set")

engine = create_engine(DATABASE_URL)

def export_table(table_name):
    with engine.connect() as conn:
        rows = conn.execute(text(f"SELECT * FROM {table_name}")).mappings().all()
    df = pd.DataFrame(rows)
    df.to_csv(f"{table_name}.csv", index=False)
    print(f"{table_name}: {len(df)} rows exported")

tables = [
    "users",
    "user_activity_log",
    "customer_features",
    "customer_predictions"
]

for t in tables:
    export_table(t)

users: 208 rows exported
user_activity_log: 1064 rows exported
customer_features: 208 rows exported
customer_predictions: 208 rows exported

In [8]:
!pip install pandas sqlalchemy python-dotenv psycopg2-binary seaborn matplotlib

Requirement already satisfied: pandas in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: sqlalchemy in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (2.0.49)
Requirement already satisfied: python-dotenv in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (1.2.2)
Requirement already satisfied: psycopg2-binary in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (2.9.11)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: greenlet>=1 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from matplotlib) (26.1)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Thato Bilankulu\Documents\jsdashboard\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   -- ------------------------------------- 0.5/7.2 MB 132.7 kB/s eta 0:00:51
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ---- ----------------------------------- 0.8/7.2 MB 102.1 kB/s eta 0:01:03
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ----- ---------------------------------- 1.0/7.2 MB 103.7 kB/s eta 0:01:00
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   ------- -------------------------------- 1.3/7.2 MB 96.2 kB/s eta 0:01:02
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   -------- ------------------------------- 1.6/7.2 MB 95.5 kB/s eta 0:01:00
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ---------- ----------------------------- 1.8/7.2 MB 99.3 kB/s eta 0:00:55
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ----------- ---------------------------- 2.1/7.2 MB 105.0 kB/s eta 0:00:49
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   ------------- -------------------------- 2.4/7.2 MB 105.3 kB/s eta 0:00:47
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   -------------- ------------------------- 2.6/7.2 MB 101.6 kB/s eta 0:00:46
   --------------- ------------------------ 2.9/7.2 MB 106.2 kB/s eta 0:00:41
   --------------- ------------------------ 2.9/7.2 MB 106.2 kB/s eta 0:00:41
   --------------- ------------------------ 2.9/7.2 MB 106.2 kB/s eta 0:00:41
   --------------- ------------------------ 2.9/7.2 MB 106.2 kB/s eta 0:00:41
   --------------- ------------------------ 2.9/7.2 MB 106.2 kB/s eta 0:00:41
   ----------------- ---------------------- 3.1/7.2 MB 112.3 kB/s eta 0:00:37
   ----------------- ---------------------- 3.1/7.2 MB 112.3 kB/s eta 0:00:37
   ----------------- ---------------------- 3.1/7.2 MB 112.3 kB/s eta 0:00:37
   ----------------- ---------------------- 3.1/7.2 MB 112.3 kB/s eta 0:00:37
   ----------------- ---------------------- 3.1/7.2 MB 112.3 kB/s eta 0:00:37
   ------------------ --------------------- 3.4/7.2 MB 117.8 kB/s eta 0:00:33
   ------------------ --------------------- 3.4/7.2 MB 117.8 kB/s eta 0:00:33
   ------------------ --------------------- 3.4/7.2 MB 117.8 kB/s eta 0:00:33
   ------------------ --------------------- 3.4/7.2 MB 117.8 kB/s eta 0:00:33
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 123.1 kB/s eta 0:00:29
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   --------------------- ------------------ 3.9/7.2 MB 125.7 kB/s eta 0:00:27
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ----------------------- ---------------- 4.2/7.2 MB 128.1 kB/s eta 0:00:24
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   ------------------------ --------------- 4.5/7.2 MB 135.5 kB/s eta 0:00:21
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   -------------------------- ------------- 4.7/7.2 MB 131.3 kB/s eta 0:00:20
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 135.1 kB/s eta 0:00:17
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 142.9 kB/s eta 0:00:14
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------ --------- 5.5/7.2 MB 146.1 kB/s eta 0:00:12
   ------------------------------- -------- 5.8/7.2 MB 149.9 kB/s eta 0:00:10
   ------------------------------- -------- 5.8/7.2 MB 149.9 kB/s eta 0:00:10
   ------------------------------- -------- 5.8/7.2 MB 149.9 kB/s eta 0:00:10
   ------------------------------- -------- 5.8/7.2 MB 149.9 kB/s eta 0:00:10
   ------------------------------- -------- 5.8/7.2 MB 149.9 kB/s eta 0:00:10
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   --------------------------------- ------ 6.0/7.2 MB 153.1 kB/s eta 0:00:08
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06
   ---------------------------------- ----- 6.3/7.2 MB 156.8 kB/s eta 0:00:06

In [14]:
users = pd.read_csv("users.csv")
activity = pd.read_csv("user_activity_log.csv")
features = pd.read_csv("customer_features.csv")
preds = pd.read_csv("customer_predictions.csv")

In [16]:
activity

,id,user_id,activity_type,activity_time,ip_address,device_info
0,1,91151fc2-6737-4227-a82c-a5c54a570061,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
1,2,12358cda-0216-49c2-bd64-ee214a4625ec,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
2,3,850ce265-7b89-45ec-802d-f4f66efef2ba,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
3,4,ee2497c8-8392-4949-a114-ef49c24ef6f5,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows
4,5,f5185eb7-7ac4-4ade-84bf-2634f95f1398,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows
...,...,...,...,...,...,...
1059,1060,202bb672-02df-4b12-852b-e9c494e08075,login,2026-03-30 01:02:55.090154,NaN,NaN
1060,1061,025859fd-05d6-4806-b208-c0355f337786,login,2026-03-15 05:08:01.987314,NaN,NaN
1061,1062,96478da8-140f-4098-8d93-10d1078ee7e4,login,2026-03-16 16:52:30.596205,NaN,NaN
1062,1063,12f00068-7e65-4d00-8ea4-25ca65ab7a58,login,2026-04-08 04:58:27.605548,NaN,NaN
1063,1064,bfc7fcfc-7db0-43c4-8d13-aa9b5f88e1ed,login,2026-03-13 17:35:53.838061,NaN,NaN

In [17]:
activity['activity_time'] = pd.to_datetime(activity['activity_time'])
activity.head()

,id,user_id,activity_type,activity_time,ip_address,device_info
0,1,91151fc2-6737-4227-a82c-a5c54a570061,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
1,2,12358cda-0216-49c2-bd64-ee214a4625ec,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
2,3,850ce265-7b89-45ec-802d-f4f66efef2ba,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
3,4,ee2497c8-8392-4949-a114-ef49c24ef6f5,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows
4,5,f5185eb7-7ac4-4ade-84bf-2634f95f1398,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows

In [22]:
user_activity_log = pd.read_csv("user_activity_log.csv")
user_activity_log.head()

,id,user_id,activity_type,activity_time,ip_address,device_info
0,1,91151fc2-6737-4227-a82c-a5c54a570061,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
1,2,12358cda-0216-49c2-bd64-ee214a4625ec,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
2,3,850ce265-7b89-45ec-802d-f4f66efef2ba,login,2026-04-02 21:42:07.002881,192.168.1.10,Chrome on Windows
3,4,ee2497c8-8392-4949-a114-ef49c24ef6f5,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows
4,5,f5185eb7-7ac4-4ade-84bf-2634f95f1398,login,2026-04-01 21:42:07.002881,192.168.1.20,Edge on Windows

In [23]:
users["id"] = users["id"].astype(str)
features["user_id"] = features["user_id"].astype(str)
preds["user_id"] = preds["user_id"].astype(str)

df = (
    users.merge(features, left_on="id", right_on="user_id", how="left")
         .merge(preds, left_on="id", right_on="user_id", how="left", suffixes=("", "_pred"))
)

df.head()

,id,full_name_x,email_x,role_x,status_x,country,is_verified_x,created_at_x,updated_at,last_login_at_x,...,churned,user_id_pred,churn_probability,risk_score,risk_level,top_reason_1,top_reason_2,top_reason_3,model_version,scored_at
0,12358cda-0216-49c2-bd64-ee214a4625ec,Jane Smith,jane@example.com,teacher,active,South Africa,True,2026-03-16 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-08 08:32:35.675309,...,0,12358cda-0216-49c2-bd64-ee214a4625ec,0.00,0.0,Low,NaN,NaN,NaN,rules_v1,2026-04-15 09:25:14.614193
1,ee2497c8-8392-4949-a114-ef49c24ef6f5,Neo Mokoena,neo@example.com,student,suspended,South Africa,False,2026-03-22 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-04 08:32:35.675309,...,0,ee2497c8-8392-4949-a114-ef49c24ef6f5,0.85,85.0,High,Account is suspended,User is not verified,4 failed login attempts,rules_v1,2026-04-15 09:25:14.614193
2,eb4fa733-2102-4ff6-971c-ec351385a8a8,Sarah Lee,sarah@example.com,admin,active,Kenya,True,2026-03-26 10:04:10.464386,2026-04-03 21:42:07.002881,2026-03-08 08:32:35.675309,...,0,eb4fa733-2102-4ff6-971c-ec351385a8a8,0.25,25.0,Low,No login for 37 days,No logins in last 7 days,NaN,rules_v1,2026-04-15 09:25:14.614193
3,e4a958af-7965-4bea-8498-1f6f669eca39,Mike Brown,mike@example.com,user,inactive,Botswana,False,2026-03-30 10:04:10.464386,2026-04-03 21:42:07.002881,2026-02-20 08:32:35.675309,...,1,e4a958af-7965-4bea-8498-1f6f669eca39,0.45,45.0,Medium,User is not verified,No login for 53 days,No logins in last 7 days,rules_v1,2026-04-15 09:25:14.614193
4,850ce265-7b89-45ec-802d-f4f66efef2ba,Alice Dube,alice@example.com,student,active,Zimbabwe,True,2026-04-03 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-09 04:32:35.675309,...,0,850ce265-7b89-45ec-802d-f4f66efef2ba,0.00,0.0,Low,NaN,NaN,NaN,rules_v1,2026-04-15 09:25:14.614193

In [13]:
print(activity.columns.tolist())

['id', 'user_id', 'activity_type', 'activity_time', 'ip_address', 'device_info']

In [26]:
df.columns.tolist()

['id',
 'full_name_x',
 'email_x',
 'role_x',
 'status_x',
 'country',
 'is_verified_x',
 'created_at_x',
 'updated_at',
 'last_login_at_x',
 'failed_login_attempts_x',
 'password_hash',
 'user_id',
 'full_name_y',
 'email_y',
 'role_y',
 'status_y',
 'is_verified_y',
 'created_at_y',
 'last_login_at_y',
 'failed_login_attempts_y',
 'days_since_last_login',
 'login_count_7d',
 'login_count_30d',
 'created_days_ago',
 'churned',
 'user_id_pred',
 'churn_probability',
 'risk_score',
 'risk_level',
 'top_reason_1',
 'top_reason_2',
 'top_reason_3',
 'model_version',
 'scored_at']

In [27]:
users.head()

,id,full_name,email,role,status,country,is_verified,created_at,updated_at,last_login_at,failed_login_attempts,password_hash
0,12358cda-0216-49c2-bd64-ee214a4625ec,Jane Smith,jane@example.com,teacher,active,South Africa,True,2026-03-16 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-08 08:32:35.675309,1,NaN
1,ee2497c8-8392-4949-a114-ef49c24ef6f5,Neo Mokoena,neo@example.com,student,suspended,South Africa,False,2026-03-22 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-04 08:32:35.675309,4,NaN
2,eb4fa733-2102-4ff6-971c-ec351385a8a8,Sarah Lee,sarah@example.com,admin,active,Kenya,True,2026-03-26 10:04:10.464386,2026-04-03 21:42:07.002881,2026-03-08 08:32:35.675309,0,NaN
3,e4a958af-7965-4bea-8498-1f6f669eca39,Mike Brown,mike@example.com,user,inactive,Botswana,False,2026-03-30 10:04:10.464386,2026-04-03 21:42:07.002881,2026-02-20 08:32:35.675309,2,NaN
4,850ce265-7b89-45ec-802d-f4f66efef2ba,Alice Dube,alice@example.com,student,active,Zimbabwe,True,2026-04-03 10:04:10.464386,2026-04-03 21:42:07.002881,2026-04-09 04:32:35.675309,0,NaN